version: '3'

services:
    mongodb:
        image: mongo
        restart: always
        ports: 
            - '27017:27017'
        volumes: 
            - ./data:/data/db
        networks:
            - backend
    
    foodz_backend:
        build: .
        env_file:
            - .env
        ports:
            - '1337:1337'
        depends_on:
            - mongodb
        networks:
            - backend
networks:
    backend:
        driver: bridge